// CDlgSettingBDI[S]
#define STR_DSBDI_00	_T("이름과 도면 이미지 파일 경로를 설정해 주세요.")
#define STR_DSBDI_01	_T("더 이상 기본 도면을 추가할 수 없습니다.\n기본 도면의 최대 갯수는 128개 입니다.")
#define STR_DSBDI_02	_T("기본 도면이 없습니다. 먼저 기본 도면을 추가해 주세요.")
#define STR_DSBDI_03	_T("더 이상 부속 도면을 추가할 수 없습니다.\n부속 도면의 최대 갯수는 128개 입니다.")
#define STR_DSBDI_04	_T("먼저 수정할 도면을 선택해 주세요.")
#define STR_DSBDI_05	_T("도면 이미지 파일 경로를 변경하셨습니다.\n내부의 모든 장치 배치 정보가 초기화 됩니다.\n계속하시겠습니까?")
#define STR_DSBDI_06	_T("먼저 삭제할 도면을 선택해 주세요.")
#define STR_DSBDI_07	_T("기본 도면을 삭제하면 기본 도면에 부속된 부속 도면들도 전부 삭제됩니다.\n계속하시겠습니까?")
#define STR_DSBDI_08	_T("선택한 도면과 장치 배치 정보를 삭제하시겠습니까?")
#define STR_DSBDI_09	_T("USM")
#define STR_DSBDI_10	_T("LGM")
#define STR_DSBDI_11	_T("더이상 장치를 도면에 추가할 수 없습니다.\n한 도면에서 표시 가능한 최대 장치 갯수는 8192 개 입니다.")
#define STR_DSBDI_12	_T("선택된 SCM 에 속한 모든 USM 장치가 도면에 배치되어 있습니다.")
#define STR_DSBDI_13	_T("선택된 SCM 에 속한 모든 LGM 장치가 도면에 배치되어 있습니다.")
#define STR_DSBDI_14	_T("선택한 장치를 도면에서 삭제하시겠습니까?")
#define STR_DSBDI_15	_T("선택 가능한 USM 장치가 없습니다.")
#define STR_DSBDI_16	_T("선택 가능한 LGM 장치가 없습니다.")
// CDlgSettingBDI[E]

// CDlgSettingCDA[S]
#define STR_DSCDA_00	_T("설정 가능한 최대 CCM 장치의 갯수는 32대 입니다.\n더이상 CCM 장치를 추가할 수 없습니다.")
#define STR_DSCDA_01	_T("먼저 수정할 CCM 장치를 선택해 주세요.")
#define STR_DSCDA_02	_T("먼저 삭제할 CCM 장치를 선택해 주세요.")
#define STR_DSCDA_03	_T("CCM 장치를 삭제하시면 CCM 장치에 속해있는 모든 SCM, USM, LGM 장치들이 삭제됩니다.\n계속하시겠습니까?")
#define STR_DSCDA_04	_T("CCM 삭제")
#define STR_DSCDA_05	_T("먼저 CCM 장치를 선택해 주세요.")
#define STR_DSCDA_06	_T("CCM 장치 하나에서 제어 가능한 최대 SCM 장치의 갯수는 15대 입니다.\n더이상 SCM 장치를 추가할 수 없습니다.")
#define STR_DSCDA_07	_T("먼저 수정할 SCM 장치를 선택해 주세요.")
#define STR_DSCDA_08	_T("먼저 삭제할 SCM 장치를 선택해 주세요.")
#define STR_DSCDA_09	_T("SCM 장치를 삭제하시면 SCM 장치에 속해있는 모든 USM, LGM 장치들이 삭제됩니다.\n계속하시겠습니까?")
#define STR_DSCDA_10	_T("SCM 삭제")
#define STR_DSCDA_11	_T("먼저 SCM 장치를 선택해 주세요.")
#define STR_DSCDA_12	_T("SCM 장치 하나에서 제어 가능한 최대 USM 장치의 갯수는 127대 입니다.\n더이상 USM 장치를 추가할 수 없습니다.")
#define STR_DSCDA_13	_T("제어 ID 가 최대값에 도달하여, %d 개의 USM 장치만 추가되었습니다.")
#define STR_DSCDA_14	_T("먼저 수정할 USM 장치를 선택해 주세요.")
#define STR_DSCDA_15	_T("USM 장치는 1개씩 수정이 가능합니다.\n1개의 USM 장치만 선택해 주세요.")
#define STR_DSCDA_16	_T("먼저 삭제할 USM 장치를 선택해 주세요.")
#define STR_DSCDA_17	_T("정말로 선택하신 USM 장치를 삭제하시겠습니까?")
#define STR_DSCDA_18	_T("USM 삭제")
#define STR_DSCDA_19	_T("SCM 장치 하나에서 제어 가능한 최대 LGM 장치의 갯수는 127대 입니다.\n더이상 LGM 장치를 추가할 수 없습니다.")
#define STR_DSCDA_20	_T("제어 ID 가 최대값에 도달하여, %d 개의 LGM 장치만 추가되었습니다.")
#define STR_DSCDA_21	_T("먼저 수정할 LGM 장치를 선택해 주세요.")
#define STR_DSCDA_22	_T("LGM 장치는 1개씩 수정이 가능합니다.\n1개의 LGM 장치만 선택해 주세요.")
#define STR_DSCDA_23	_T("먼저 삭제할 LGM 장치를 선택해 주세요.")
#define STR_DSCDA_24	_T("정말로 선택하신 LGM 장치를 삭제하시겠습니까?")
#define STR_DSCDA_25	_T("LGM 삭제")
// CDlgSettingCDA[E]